### ISSUE TITLE
Cannot run outside of development environment

### ISSUE THREAD

**Issue by solonovamax** [PolyhedralDev/BiomeTool#6]
Application does not extract addons and dump them into the correct directory structure, thus it cannot run outside the preconfigured gradle env.

Logs:

```
2022-03-27 21:59:29,752 [main]                           INFO  com.dfsek.terra.biometool.BiomeToolLauncher                      - Starting BiomeTool application.
28, 2022 2:41:18 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6a472554'
28, 2022 2:41:18 AM tornadofx.Stylesheet$Companion detectAndInstallUrlHandler
INFO: Installing CSS url handler, since it was not picked up automatically
2022-03-27 21:59:30,429 [JavaFX Application Thread]      INFO  com.dfsek.terra.biometool.BiomeToolView                          - Initializing Terra platform...
2022-03-27 21:59:30,448 [JavaFX Application Thread]      INFO  com.dfsek.terra.biometool.BiomeToolPlatform                      - Root directory: C:\Users\Zelef\.
2022-03-27 21:59:30,449 [JavaFX Application Thread]      INFO  com.dfsek.terra.AbstractPlatform                                 - Initializing Terra...
2022-03-27 21:59:30,459 [JavaFX Application Thread]      INFO  com.dfsek.terra.config.PluginConfigImpl                          - Loading config values from config.yml
2022-03-27 21:59:30,526 [JavaFX Application Thread]      DEBUG com.dfsek.terra.addon.BootstrapAddonLoader                       - Loading bootstrap addons from .\addons\bootstrap
Exception in Application start method
2022-03-27 21:59:30,530 [JavaFX Application Thread]      INFO  com.dfsek.terra.biometool.BiomeToolView                          - Initializing Terra platform...
Exception in Application stop method
28, 2022 2:41:18 AM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError
        at com.dfsek.terra.biometool.BiomeToolView.<init>(BiomeToolView.kt:75)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
... (33 lines left)
```

**Comment by Roan-V** [comment]
Not sure if related to WSL (WSLg should be able to run GUI programs, but I have never tried it before myself), currently unable to try on an actual linux install
But can confirm I get the same error

```
roan@P400A:~/Terra$ java -jar BiomeTool-0.4.8-all.jar
2023-12-21 12:26:14,647 [main]                   INFO  com.dfsek.terra.biometool.BiomeToolLauncher      - Starting BiomeTool application.
Dec 21, 2023 12:26:14 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @75eeccf5'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /home/roan/.openjfx/cache/17.0.9/libprism_es2.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/roan/.openjfx/cache/17.0.9/libprism_es2.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
        at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.base/java.lang.Thread.run(Thread.java:840)
Exception in thread "main" java.lang.UnsupportedOperationException: Internal Error
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:179)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:840)
```
